plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
}

repositories {
    //mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/ing-sist/printscript")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

def psVersion = "3.0-SNAPSHOT"
def psModules = [
        "lexer",
        "formatter",
        "token",
        "parser",
        "interpreter",
        "ast",
        "cli",
        "common",
        "analyzer"
]

dependencies {
    testImplementation 'junit:junit:4.13.1'
    psModules.each { module ->
        implementation("org.printscript:${module}:${psVersion}")
    }
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
